# Generated by Django 4.1.3 on 2022-12-21 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('text', models.TextField(max_length=1000, verbose_name='основной текст')),
                ('image', models.ImageField(upload_to='blog/images/', verbose_name='изображение')),
                ('date', models.DateField(verbose_name='дата публикации')),
                ('time', models.TimeField(verbose_name='время публикации')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
